# Generated by Django 6.0.2 on 2026-02-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('None', 'One Time'), ('Daily', 'Everyday'), ('Weekdays', 'Weekdays'), ('Weekend', 'Weekend')], default='None', max_length=20),
        ),
    ]
