# Generated by Django 6.0.2 on 2026-02-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
