# Generated by Django 6.0.2 on 2026-02-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('None', 'One Time'), ('Daily', 'Everyday'), ('Weekdays', 'Weekdays'), ('Weekend', 'Weekend'), ('Custom', 'Custom')], default='None', max_length=20),
        ),
    ]
